version: "3.9"

services:
  caddy:
    container_name: caddy
    image: caddy-custom:latest
    network_mode: "host"
    restart: always
    volumes:
       - ./Caddyfile:/etc/caddy/Caddyfile
       - ./certs:/certs
       - ./config:/config
       - ./data:/data
       - ./sites:/srv
